package com.lrx.Dao.System;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.lrx.Model.System.TDepartment;
import com.lrx.Model.System.TDepartmentExample;

public interface TDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_DEPARTMENT
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int countByExample(TDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_DEPARTMENT
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int deleteByExample(TDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_DEPARTMENT
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int insert(TDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_DEPARTMENT
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int insertSelective(TDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_DEPARTMENT
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    List<TDepartment> selectByExample(TDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_DEPARTMENT
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") TDepartment record, @Param("example") TDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_DEPARTMENT
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int updateByExample(@Param("record") TDepartment record, @Param("example") TDepartmentExample example);
    
	int updateByPrimaryKeySelective(TDepartment record);
	int deleteByPrimaryKey(Long id);
}