package com.lrx.Dao.System;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.lrx.Model.System.TRoleModule;
import com.lrx.Model.System.TRoleModuleExample;

public interface TRoleModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_ROLE_MODULE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int countByExample(TRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_ROLE_MODULE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int deleteByExample(TRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_ROLE_MODULE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int insert(TRoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_ROLE_MODULE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int insertSelective(TRoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_ROLE_MODULE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    List<TRoleModule> selectByExample(TRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_ROLE_MODULE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") TRoleModule record, @Param("example") TRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.T_ROLE_MODULE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int updateByExample(@Param("record") TRoleModule record, @Param("example") TRoleModuleExample example);
}