package com.lrx.Dao.System;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lrx.Model.System.TDepartMentRole;
import com.lrx.Model.System.VDepartmentUser;
import com.lrx.Model.System.VDepartmentUserExample;

public interface VDepartmentUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.V_DEPARTMENT_USER
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int countByExample(VDepartmentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.V_DEPARTMENT_USER
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int deleteByExample(VDepartmentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.V_DEPARTMENT_USER
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int insert(VDepartmentUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.V_DEPARTMENT_USER
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int insertSelective(VDepartmentUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.V_DEPARTMENT_USER
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    List<VDepartmentUser> selectByExample(VDepartmentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.V_DEPARTMENT_USER
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") VDepartmentUser record, @Param("example") VDepartmentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OBERACIIS_FUEL.V_DEPARTMENT_USER
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    int updateByExample(@Param("record") VDepartmentUser record, @Param("example") VDepartmentUserExample example);
    
	List<VDepartmentUser> getDepartMentUser(TDepartMentRole cond);
}