package com.lrx.Model.System;

public class TDepartment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_DEPARTMENT.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_DEPARTMENT.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_DEPARTMENT.CODE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_DEPARTMENT.DISPLAY_INDEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long displayIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_DEPARTMENT.FULL_PATH_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String fullPathName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_DEPARTMENT.FULL_PATH_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String fullPathId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_DEPARTMENT.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_DEPARTMENT.ICON
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.ID
     *
     * @return the value of OBERACIIS_FUEL.T_DEPARTMENT.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.ID
     *
     * @param id the value for OBERACIIS_FUEL.T_DEPARTMENT.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.NAME
     *
     * @return the value of OBERACIIS_FUEL.T_DEPARTMENT.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.NAME
     *
     * @param name the value for OBERACIIS_FUEL.T_DEPARTMENT.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.CODE
     *
     * @return the value of OBERACIIS_FUEL.T_DEPARTMENT.CODE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.CODE
     *
     * @param code the value for OBERACIIS_FUEL.T_DEPARTMENT.CODE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.DISPLAY_INDEX
     *
     * @return the value of OBERACIIS_FUEL.T_DEPARTMENT.DISPLAY_INDEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getDisplayIndex() {
        return displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.DISPLAY_INDEX
     *
     * @param displayIndex the value for OBERACIIS_FUEL.T_DEPARTMENT.DISPLAY_INDEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setDisplayIndex(Long displayIndex) {
        this.displayIndex = displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.FULL_PATH_NAME
     *
     * @return the value of OBERACIIS_FUEL.T_DEPARTMENT.FULL_PATH_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getFullPathName() {
        return fullPathName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.FULL_PATH_NAME
     *
     * @param fullPathName the value for OBERACIIS_FUEL.T_DEPARTMENT.FULL_PATH_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setFullPathName(String fullPathName) {
        this.fullPathName = fullPathName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.FULL_PATH_ID
     *
     * @return the value of OBERACIIS_FUEL.T_DEPARTMENT.FULL_PATH_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getFullPathId() {
        return fullPathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.FULL_PATH_ID
     *
     * @param fullPathId the value for OBERACIIS_FUEL.T_DEPARTMENT.FULL_PATH_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setFullPathId(String fullPathId) {
        this.fullPathId = fullPathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.PARENT_ID
     *
     * @return the value of OBERACIIS_FUEL.T_DEPARTMENT.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.PARENT_ID
     *
     * @param parentId the value for OBERACIIS_FUEL.T_DEPARTMENT.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.ICON
     *
     * @return the value of OBERACIIS_FUEL.T_DEPARTMENT.ICON
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_DEPARTMENT.ICON
     *
     * @param icon the value for OBERACIIS_FUEL.T_DEPARTMENT.ICON
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }
}