package com.lrx.Model.System;

import java.util.Date;

public class TModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.DESCRIPTION
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.VERSION
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.DISPLAY_INDEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long displayIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.MODULE_URL
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String moduleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.ICON
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.PUBLISHED
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Date published;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.RELEASE_USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String releaseUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.TYPE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.WORKFLOW_KEY
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String workflowKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_MODULE.ACCESS_CONTROL
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long accessControl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.ID
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.ID
     *
     * @param id the value for OBERACIIS_FUEL.T_MODULE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.NAME
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.NAME
     *
     * @param name the value for OBERACIIS_FUEL.T_MODULE.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.DESCRIPTION
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.DESCRIPTION
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.DESCRIPTION
     *
     * @param description the value for OBERACIIS_FUEL.T_MODULE.DESCRIPTION
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.VERSION
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.VERSION
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.VERSION
     *
     * @param version the value for OBERACIIS_FUEL.T_MODULE.VERSION
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.DISPLAY_INDEX
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.DISPLAY_INDEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getDisplayIndex() {
        return displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.DISPLAY_INDEX
     *
     * @param displayIndex the value for OBERACIIS_FUEL.T_MODULE.DISPLAY_INDEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setDisplayIndex(Long displayIndex) {
        this.displayIndex = displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.MODULE_URL
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.MODULE_URL
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.MODULE_URL
     *
     * @param moduleUrl the value for OBERACIIS_FUEL.T_MODULE.MODULE_URL
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.ICON
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.ICON
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.ICON
     *
     * @param icon the value for OBERACIIS_FUEL.T_MODULE.ICON
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.PUBLISHED
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.PUBLISHED
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Date getPublished() {
        return published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.PUBLISHED
     *
     * @param published the value for OBERACIIS_FUEL.T_MODULE.PUBLISHED
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setPublished(Date published) {
        this.published = published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.RELEASE_USER_ID
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.RELEASE_USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getReleaseUserId() {
        return releaseUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.RELEASE_USER_ID
     *
     * @param releaseUserId the value for OBERACIIS_FUEL.T_MODULE.RELEASE_USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setReleaseUserId(String releaseUserId) {
        this.releaseUserId = releaseUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.PARENT_ID
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.PARENT_ID
     *
     * @param parentId the value for OBERACIIS_FUEL.T_MODULE.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.TYPE
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.TYPE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.TYPE
     *
     * @param type the value for OBERACIIS_FUEL.T_MODULE.TYPE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setType(Long type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.WORKFLOW_KEY
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.WORKFLOW_KEY
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getWorkflowKey() {
        return workflowKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.WORKFLOW_KEY
     *
     * @param workflowKey the value for OBERACIIS_FUEL.T_MODULE.WORKFLOW_KEY
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setWorkflowKey(String workflowKey) {
        this.workflowKey = workflowKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_MODULE.ACCESS_CONTROL
     *
     * @return the value of OBERACIIS_FUEL.T_MODULE.ACCESS_CONTROL
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getAccessControl() {
        return accessControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_MODULE.ACCESS_CONTROL
     *
     * @param accessControl the value for OBERACIIS_FUEL.T_MODULE.ACCESS_CONTROL
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setAccessControl(Long accessControl) {
        this.accessControl = accessControl;
    }
}