package com.lrx.Model.System;

import java.util.Date;

public class TRoleModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE_MODULE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE_MODULE.ROLE_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE_MODULE.MODULE_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long moduleId;
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	private String moduleName;
	
	private String description;

    public String getModuleName() {
		return moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE_MODULE.TIME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE_MODULE.USER_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE_MODULE.SELECT_FLAG
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long selectFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.ID
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE_MODULE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.ID
     *
     * @param id the value for OBERACIIS_FUEL.T_ROLE_MODULE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.ROLE_ID
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE_MODULE.ROLE_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.ROLE_ID
     *
     * @param roleId the value for OBERACIIS_FUEL.T_ROLE_MODULE.ROLE_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.MODULE_ID
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE_MODULE.MODULE_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.MODULE_ID
     *
     * @param moduleId the value for OBERACIIS_FUEL.T_ROLE_MODULE.MODULE_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.TIME
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE_MODULE.TIME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.TIME
     *
     * @param time the value for OBERACIIS_FUEL.T_ROLE_MODULE.TIME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.USER_NAME
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE_MODULE.USER_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.USER_NAME
     *
     * @param userName the value for OBERACIIS_FUEL.T_ROLE_MODULE.USER_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.SELECT_FLAG
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE_MODULE.SELECT_FLAG
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getSelectFlag() {
        return selectFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE_MODULE.SELECT_FLAG
     *
     * @param selectFlag the value for OBERACIIS_FUEL.T_ROLE_MODULE.SELECT_FLAG
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setSelectFlag(Long selectFlag) {
        this.selectFlag = selectFlag;
    }
}