package com.lrx.Model.System;

public class TRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE.CODE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE.DISPLAY_INDEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long displayIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE.DESCRIPTION
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_ROLE.TYPE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE.ID
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE.ID
     *
     * @param id the value for OBERACIIS_FUEL.T_ROLE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE.NAME
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE.NAME
     *
     * @param name the value for OBERACIIS_FUEL.T_ROLE.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE.CODE
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE.CODE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE.CODE
     *
     * @param code the value for OBERACIIS_FUEL.T_ROLE.CODE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE.PARENT_ID
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE.PARENT_ID
     *
     * @param parentId the value for OBERACIIS_FUEL.T_ROLE.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE.DISPLAY_INDEX
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE.DISPLAY_INDEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getDisplayIndex() {
        return displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE.DISPLAY_INDEX
     *
     * @param displayIndex the value for OBERACIIS_FUEL.T_ROLE.DISPLAY_INDEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setDisplayIndex(Long displayIndex) {
        this.displayIndex = displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE.DESCRIPTION
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE.DESCRIPTION
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE.DESCRIPTION
     *
     * @param description the value for OBERACIIS_FUEL.T_ROLE.DESCRIPTION
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_ROLE.TYPE
     *
     * @return the value of OBERACIIS_FUEL.T_ROLE.TYPE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_ROLE.TYPE
     *
     * @param type the value for OBERACIIS_FUEL.T_ROLE.TYPE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setType(Long type) {
        this.type = type;
    }
}