package com.lrx.Model.System;

public class TUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.MOBILE_PHONE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.USER_PASSWORD
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.ADDRESS
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.DEPARTMENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.HISORY_PASSWORD
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String hisoryPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.SIGN_IMAGE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String signImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.ACTIVE_STATE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Short activeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.POST
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.OFFICE_PHONE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String officePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.SEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.FLOW_TAG
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Short flowTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.THEME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.T_USERS.LAYOUT
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String layout;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.ID
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.ID
     *
     * @param id the value for OBERACIIS_FUEL.T_USERS.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.NAME
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.NAME
     *
     * @param name the value for OBERACIIS_FUEL.T_USERS.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.MOBILE_PHONE
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.MOBILE_PHONE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.MOBILE_PHONE
     *
     * @param mobilePhone the value for OBERACIIS_FUEL.T_USERS.MOBILE_PHONE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.USER_ID
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.USER_ID
     *
     * @param userId the value for OBERACIIS_FUEL.T_USERS.USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.USER_PASSWORD
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.USER_PASSWORD
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.USER_PASSWORD
     *
     * @param userPassword the value for OBERACIIS_FUEL.T_USERS.USER_PASSWORD
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.ADDRESS
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.ADDRESS
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.ADDRESS
     *
     * @param address the value for OBERACIIS_FUEL.T_USERS.ADDRESS
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.DEPARTMENT_ID
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.DEPARTMENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.DEPARTMENT_ID
     *
     * @param departmentId the value for OBERACIIS_FUEL.T_USERS.DEPARTMENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.HISORY_PASSWORD
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.HISORY_PASSWORD
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getHisoryPassword() {
        return hisoryPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.HISORY_PASSWORD
     *
     * @param hisoryPassword the value for OBERACIIS_FUEL.T_USERS.HISORY_PASSWORD
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setHisoryPassword(String hisoryPassword) {
        this.hisoryPassword = hisoryPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.SIGN_IMAGE
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.SIGN_IMAGE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getSignImage() {
        return signImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.SIGN_IMAGE
     *
     * @param signImage the value for OBERACIIS_FUEL.T_USERS.SIGN_IMAGE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setSignImage(String signImage) {
        this.signImage = signImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.ACTIVE_STATE
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.ACTIVE_STATE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Short getActiveState() {
        return activeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.ACTIVE_STATE
     *
     * @param activeState the value for OBERACIIS_FUEL.T_USERS.ACTIVE_STATE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setActiveState(Short activeState) {
        this.activeState = activeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.POST
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.POST
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.POST
     *
     * @param post the value for OBERACIIS_FUEL.T_USERS.POST
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setPost(String post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.OFFICE_PHONE
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.OFFICE_PHONE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.OFFICE_PHONE
     *
     * @param officePhone the value for OBERACIIS_FUEL.T_USERS.OFFICE_PHONE
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.SEX
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.SEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.SEX
     *
     * @param sex the value for OBERACIIS_FUEL.T_USERS.SEX
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.FLOW_TAG
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.FLOW_TAG
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Short getFlowTag() {
        return flowTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.FLOW_TAG
     *
     * @param flowTag the value for OBERACIIS_FUEL.T_USERS.FLOW_TAG
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setFlowTag(Short flowTag) {
        this.flowTag = flowTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.THEME
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.THEME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.THEME
     *
     * @param theme the value for OBERACIIS_FUEL.T_USERS.THEME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.T_USERS.LAYOUT
     *
     * @return the value of OBERACIIS_FUEL.T_USERS.LAYOUT
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getLayout() {
        return layout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.T_USERS.LAYOUT
     *
     * @param layout the value for OBERACIIS_FUEL.T_USERS.LAYOUT
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setLayout(String layout) {
        this.layout = layout;
    }
}