package com.lrx.Model.System;

public class VDepartmentUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.ICON
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Short userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.ID
     *
     * @return the value of OBERACIIS_FUEL.V_DEPARTMENT_USER.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    /*2016-3-24 liruoxiu begin*/
    private String userCode;
    
    public String getUserCode() {
		return userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}
	/*2016-3-24 end*/
	public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.ID
     *
     * @param id the value for OBERACIIS_FUEL.V_DEPARTMENT_USER.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.NAME
     *
     * @return the value of OBERACIIS_FUEL.V_DEPARTMENT_USER.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.NAME
     *
     * @param name the value for OBERACIIS_FUEL.V_DEPARTMENT_USER.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.PARENT_ID
     *
     * @return the value of OBERACIIS_FUEL.V_DEPARTMENT_USER.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.PARENT_ID
     *
     * @param parentId the value for OBERACIIS_FUEL.V_DEPARTMENT_USER.PARENT_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.ICON
     *
     * @return the value of OBERACIIS_FUEL.V_DEPARTMENT_USER.ICON
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.ICON
     *
     * @param icon the value for OBERACIIS_FUEL.V_DEPARTMENT_USER.ICON
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.USER_ID
     *
     * @return the value of OBERACIIS_FUEL.V_DEPARTMENT_USER.USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Short getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_DEPARTMENT_USER.USER_ID
     *
     * @param userId the value for OBERACIIS_FUEL.V_DEPARTMENT_USER.USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setUserId(Short userId) {
        this.userId = userId;
    }
}