package com.lrx.Model.System;

import java.util.Date;

public class VUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_USER_ROLE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_USER_ROLE.TIME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_USER_ROLE.USER_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_USER_ROLE.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_USER_ROLE.USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OBERACIIS_FUEL.V_USER_ROLE.FULL_PATH_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    private String fullPathName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_USER_ROLE.ID
     *
     * @return the value of OBERACIIS_FUEL.V_USER_ROLE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_USER_ROLE.ID
     *
     * @param id the value for OBERACIIS_FUEL.V_USER_ROLE.ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_USER_ROLE.ROLE_ID
     *
     * @return the value of OBERACIIS_FUEL.V_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_USER_ROLE.ROLE_ID
     *
     * @param roleId the value for OBERACIIS_FUEL.V_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_USER_ROLE.TIME
     *
     * @return the value of OBERACIIS_FUEL.V_USER_ROLE.TIME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_USER_ROLE.TIME
     *
     * @param time the value for OBERACIIS_FUEL.V_USER_ROLE.TIME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_USER_ROLE.USER_NAME
     *
     * @return the value of OBERACIIS_FUEL.V_USER_ROLE.USER_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_USER_ROLE.USER_NAME
     *
     * @param userName the value for OBERACIIS_FUEL.V_USER_ROLE.USER_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_USER_ROLE.NAME
     *
     * @return the value of OBERACIIS_FUEL.V_USER_ROLE.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_USER_ROLE.NAME
     *
     * @param name the value for OBERACIIS_FUEL.V_USER_ROLE.NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_USER_ROLE.USER_ID
     *
     * @return the value of OBERACIIS_FUEL.V_USER_ROLE.USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_USER_ROLE.USER_ID
     *
     * @param userId the value for OBERACIIS_FUEL.V_USER_ROLE.USER_ID
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OBERACIIS_FUEL.V_USER_ROLE.FULL_PATH_NAME
     *
     * @return the value of OBERACIIS_FUEL.V_USER_ROLE.FULL_PATH_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public String getFullPathName() {
        return fullPathName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OBERACIIS_FUEL.V_USER_ROLE.FULL_PATH_NAME
     *
     * @param fullPathName the value for OBERACIIS_FUEL.V_USER_ROLE.FULL_PATH_NAME
     *
     * @mbggenerated Thu May 14 11:49:07 CST 2015
     */
    public void setFullPathName(String fullPathName) {
        this.fullPathName = fullPathName;
    }
}